# Generated by Django 5.2 on 2025-04-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surfboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('shortboard', 'Shortboard'), ('longboard', 'Longboard'), ('fish', 'Fish'), ('funboard', 'Funboard')], max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('length', models.FloatField()),
                ('length_units', models.CharField(choices=[('cm', 'cm'), ('inches', 'inches'), ('feet', 'feet'), ('liters', 'liters')], default='feet', max_length=10)),
                ('width', models.FloatField()),
                ('width_units', models.CharField(choices=[('cm', 'cm'), ('inches', 'inches'), ('feet', 'feet'), ('liters', 'liters')], default='inches', max_length=10)),
                ('thickness', models.FloatField()),
                ('thickness_units', models.CharField(choices=[('cm', 'cm'), ('inches', 'inches'), ('feet', 'feet'), ('liters', 'liters')], default='inches', max_length=10)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=4)),
                ('volume_units', models.CharField(choices=[('cm', 'cm'), ('inches', 'inches'), ('feet', 'feet'), ('liters', 'liters')], default='liters', max_length=10)),
            ],
        ),
    ]
